version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building React app..."
      - npm run build
  post_build:
    commands:
      - echo "Uploading files to S3..."
      - aws s3 sync dist/ s3://docnet-frontend-furcode --delete

artifacts:
  files:
    - '**/*'
