version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20   # ✅ Use Node 20 for React 18+ / Vite 5+ compatibility
    commands:
      - echo "Installing dependencies..."
      - npm ci || npm install  # 'npm ci' is faster and cleaner in CI/CD
  build:
    commands:
      - echo "Building React app..."
      - npm run build
  post_build:
    commands:
      - echo "Uploading files to S3..."
      - if [ -d "dist" ]; then aws s3 sync dist/ s3://docnet-frontend-furcode --delete; else echo "❌ dist folder not found!"; exit 1; fi

artifacts:
  files:
    - '**/*'
